on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
        with:
            r-version: '3.6.1'
      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install tree
        run: sudo apt-get install tree
      - name: tree
        run: tree
      - name: Install renv and rcmdcheck
        run: Rscript -e "install.packages(c('renv', 'rcmdcheck'))"
      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error')"
